# Generated by Django 5.2.13 on 2026-05-08 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finances', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'wallet', 'category', 'start_date')},
        ),
        migrations.AddField(
            model_name='budget',
            name='repeat',
            field=models.CharField(choices=[('none', 'Không lặp lại'), ('daily', 'Hằng ngày'), ('weekly', 'Hằng tuần'), ('monthly', 'Hằng tháng'), ('yearly', 'Hằng năm')], default='monthly', max_length=10),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
    ]
